[package]
name = "gensketch"
version = "0.1.0"
description = "Genomics data viewer and sketchpad"
authors = ["fennerm"]
license = "AGPL-3.0"
repository = "https://github.com/fennerm/gensketch"
default-run = "gensketch"
edition = "2021"
rust-version = "1.57"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = "1.0.4"

[dependencies]
anyhow = { version = "1.0", features = ["backtrace"] }
bio = "1.0"
bio-types = {version = "0.13", features = ["serde"] }
log = "0.4"
parking_lot = {version = "0.12", features = ["serde"] }
rust-htslib = "0.40"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "1.0.5", features = ["api-all"] }
tauri-plugin-log = { git = "https://github.com/tauri-apps/tauri-plugin-log" }
thiserror = "1.0"
typescript-definitions = { git = "https://github.com/onelson/typescript-definitions", branch = "no-debug-attrs"}
uuid = {version="1.2", features = ["serde"] }

[features]
# by default Tauri runs in production mode
# when `tauri dev` runs it is executed with `cargo run --no-default-features` if `devPath` is an URL
default = [ "custom-protocol" ]
# this feature is used used for production builds where `devPath` points to the filesystem
# DO NOT remove this
custom-protocol = [ "tauri/custom-protocol" ]
