export const TOOLBAR_HEIGHT_FRACTION = 0.1;
export const TOOLBAR_WIDTH_FRACTION = 1;
export const SPLIT_GRID_HEIGHT_FRACTION = 1 - TOOLBAR_HEIGHT_FRACTION;
export const SPLIT_GRID_WIDTH_FRACTION = 1;
export const DIVIDER_PX = 2;
